#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
 
cookbook 'postgresql', :github => 'phlipper/chef-postgresql'
cookbook 'gis', :github => 'marsam/cookbook-gis'